// <auto-generated />
using System;
using Grp19OnlineBookStorePE03.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grp19OnlineBookStorePE03.Migrations
{
    [DbContext(typeof(Grp19OnlineBookStorePE03Context))]
    partial class Grp19OnlineBookStorePE03ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Holly Black",
                            BookName = "The Cruel Prince",
                            Category = "Romance",
                            Price = 17.20m,
                            StaffId = 1
                        },
                        new
                        {
                            Id = 2,
                            Author = "Vince Elson",
                            BookName = "The Laughing King",
                            Category = "Comedy",
                            Price = 18.50m,
                            StaffId = 1
                        },
                        new
                        {
                            Id = 3,
                            Author = "Holly Black",
                            BookName = "The Queen Of Nothing",
                            Category = "Romance",
                            Price = 16.50m,
                            StaffId = 1
                        });
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "676 Tampines Drive, Stree 41",
                            ContactNum = "86605947",
                            Login = "sarah123",
                            Name = "Sarah",
                            Password = "password123"
                        });
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Misc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiscName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("Misc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Stationary",
                            MiscName = " PIX Black Ballpoint Pen",
                            Price = 450.0m,
                            StaffId = 2
                        },
                        new
                        {
                            Id = 2,
                            Category = "Office Supplies",
                            MiscName = "Canon Original Black Cartridge",
                            Price = 33.00m,
                            StaffId = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Wellness",
                            MiscName = "Hitachi HMG-900 Precision Massage Gun",
                            Price = 67.50m,
                            StaffId = 2
                        });
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("MiscId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MiscId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BookStaff",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MiscStaff",
                            Password = "321"
                        });
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Book", b =>
                {
                    b.HasOne("Grp19OnlineBookStorePE03.Classes.Staff", "Staff")
                        .WithMany("BookItems")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Misc", b =>
                {
                    b.HasOne("Grp19OnlineBookStorePE03.Classes.Staff", "Staff")
                        .WithMany("MiscItems")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Order", b =>
                {
                    b.HasOne("Grp19OnlineBookStorePE03.Classes.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.OrderItem", b =>
                {
                    b.HasOne("Grp19OnlineBookStorePE03.Classes.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.HasOne("Grp19OnlineBookStorePE03.Classes.Misc", "Misc")
                        .WithMany()
                        .HasForeignKey("MiscId");

                    b.HasOne("Grp19OnlineBookStorePE03.Classes.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.Navigation("Book");

                    b.Navigation("Misc");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Payment", b =>
                {
                    b.HasOne("Grp19OnlineBookStorePE03.Classes.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Grp19OnlineBookStorePE03.Classes.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Grp19OnlineBookStorePE03.Classes.Staff", b =>
                {
                    b.Navigation("BookItems");

                    b.Navigation("MiscItems");
                });
#pragma warning restore 612, 618
        }
    }
}
